### ISSUE TITLE
Get error as "Cannot read properties of null (reading 'once')

### ISSUE THREAD

**Issue by prajon84** [SumoLogic/sumologic-opentelemetry-js#66]
When clicked on the first item in the dropdown menu,

Getting error due to RUM javascript code as:
![image](https://user-images.githubusercontent.com/43785517/205087691-2fe0b18f-81fe-48b9-87e7-4223d5f899ef.png)

Also nothing is rendered in screen so that application is broken.
![image](https://user-images.githubusercontent.com/43785517/205147127-828226a6-c828-4dfc-836f-ea7f8c3f8cc4.png)

But, if the RUM javascript code is removed, there is no error.

Even though the issue above is irrespective of the browser.
Browser used: Chrome Version 107.0.5304.107 (Official Build) (64-bit) 
App uses: 
`react : 17.0.2` and  `react-dom: 17.0.2`
SumoLogic RUM  used: `https://rum.sumologic.com/sumologic-rum-v4.js`

Any help or idea would be appreciated 🙏

**Comment by TRybakSUMO** [comment]
Hi @prajon84, thanks for letting us know. 
I prepared a fix for that issue: https://github.com/SumoLogic/sumologic-opentelemetry-js/pull/67

**Comment by TRybakSUMO** [comment]
New version (**4.1.1**) with fix has been released:

https://rum.sumologic.com/sumologic-rum-v4.1.1.js
https://rum.sumologic.com/sumologic-rum-v4.1.js
https://rum.sumologic.com/sumologic-rum-v4.js
https://rum.sumologic.com/sumologic-rum.js

In case of any problems, please let us know.
