### ISSUE TITLE
Update @opentelemetry/api dependencies

### ISSUE THREAD

**Issue by ggotti** [SumoLogic/sumologic-opentelemetry-js#94]
The `peerDependencies` for the project are relying on OpenTelemtry API versions which were released over 2 years ago. Is there a plan to update to a later version of the `@opentelemetry/api` package?

<img width="594" alt="image" src="https://github.com/SumoLogic/sumologic-opentelemetry-js/assets/1842134/e489e65a-fe98-4945-bc71-ecd9c890f621">

<img width="836" alt="image" src="https://github.com/SumoLogic/sumologic-opentelemetry-js/assets/1842134/d7b50e22-c411-4ffa-8972-cce531c388c9">

We're having `peer dependency` issues with `NextJS`, where they have upgrade the base OpenTelemetry API version to @opentelemetry/api@1.7.0

**Comment by findmyway** [comment]
Looks like it's already been updated?

https://github.com/SumoLogic/sumologic-opentelemetry-js/blob/9588a98d7bc85cd8268af95b49d44805ad6ff74a/package.json#L68-L70

**Comment by ggotti** [comment]
We ended up raising it via our enterprise contact, and got the version bumped :)
